services:
  qstash-log-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      VITE_QSTASH_URL: http://localhost:8080
      VITE_QSTASH_TOKEN: REPLACE_ME
